### PR TITLE
Add Georgian translation

### PR DESCRIPTION
**Pull request by NorwayFun**
Hello,
I hope this time it's ok.

### CODE REVIEW

**Comment by return42** [comment]
FYI this repo is a mirror of https://sourceforge.net/p/docutils/code/HEAD/tree/trunk/

**Comment by bellaperez** [comment]
@NorwayFun Use 'Create Ticket' button from https://sourceforge.net/p/docutils/patches/ . It is my PR: [Catalan updates](https://sourceforge.net/p/docutils/patches/203/)

**Comment by NorwayFun** [comment]
Still none of them were merged :)

**Comment by grubert** [comment]
Sorry I had to have fun on a jazz workshop 😁🥳🌞🎶

NorwayFun ***@***.***> schrieb am Mi. 9. Aug. 2023 um 21:32:

**Pull request closed without merging**
